name: build

on:
  push:
    branches: [master]
    tags: ['v*']
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: Build application
        run: msbuild screenshot-history.sln -t:rebuild -verbosity:diag -property:Configuration=Release

      - name: List build output
        run: Get-ChildItem -Recurse -Name

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{ github.ref_name }} --latest screenshot-history/bin/Release/screenshot-history.exe
